version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/quotes/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - kicat_network
    ports:
      - "${WEB_PORT:-8000}:8000"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - kicat_network
    ports:
      - "${DB_PORT:-5432}:5432"
    command: >
      postgres
      -c shared_buffers=32MB
      -c effective_cache_size=128MB
      -c maintenance_work_mem=16MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=1MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200

networks:
  kicat_network:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_network

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_postgres_data
  static_volume:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_static_volume
  media_volume:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_media_volume 