version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/quotes/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - kicat_network
    expose:
      - "8000"
    labels:
      - caddy.enable=true
      - caddy=your-domain.com
      - caddy.reverse_proxy=web:8000

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - kicat_network

networks:
  kicat_network:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_network

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_postgres_data
  static_volume:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_static_volume
  media_volume:
    name: ${COMPOSE_PROJECT_NAME:-kicat}_media_volume 