# Generated by Django 5.2.1 on 2025-05-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('please_select', '서비스 선택'), ('translation', '번역'), ('interpretation', '통역'), ('others', '기타서비스')], default='please_select', max_length=255)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('quote_sent', '견적서 발송'), ('work_in_progress', '작업중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=255)),
                ('google_drive_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
